name: Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '20 8 * * 4'

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v4

      # Scan code using Semgrep Docker image
      - name: Run Semgrep Scan
        uses: docker://semgrep/semgrep:latest
        with:
          args: semgrep scan --config "p/security-audit" --config "p/python" --config "p/owasp-top-ten" --config "p/python" --config "p/trailofbits" --sarif --output=semgrep.sarif 

      # Upload SARIF file generated in previous step
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
